field.formatter.settings.inline_ad_entity:
  type: mapping
  label: 'Inline Ad Entity: Settings'
  mapping:
    ad_frequency:
      type: integer
      label: 'Number of paragraphs to skip'
    ad_display:
      type: string
      label: 'Type of Ad Entity Display to display'
